/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes otherwise-wasted capacity (surplus) and what value it could create if activated. SEP matches surplus to needs—the baseline is 'better than nothing', not 'fair market value'. Any activation of surplus is a win.
 */
export interface SurplusOffering {
  /**
   * Unique identifier for this offering
   */
  id: string;
  /**
   * Category of surplus being offered
   */
  type: "service" | "physical_good" | "access" | "space";
  /**
   * Identifier of the participant offering this surplus
   */
  provider: string;
  /**
   * Current availability status
   */
  status: "available" | "partially_committed" | "unavailable";
  /**
   * Short, human-readable title (for confirmation/scoping after match discovery)
   */
  title?: string;
  /**
   * Detailed description (for humans reviewing proposed matches)
   */
  description?: string;
  surplus_context?: SurplusContext;
  capability_matching: CapabilityMatching;
  service_details?: ServiceDetails;
  physical_details?: PhysicalDetails;
  access_details?: AccessDetails;
  constraints?: Constraints;
  [k: string]: unknown;
}
/**
 * Context establishing this as otherwise-wasted capacity
 */
export interface SurplusContext {
  /**
   * Why this capacity would otherwise go unused (e.g., 'Designer between projects', 'Excess stock from cancelled order', 'Vehicle returning empty')
   */
  why_surplus?: string;
  /**
   * What would happen to this capacity without SEP
   */
  alternative_fate?: "unused" | "discounted_sale" | "disposal" | "depreciation" | "opportunity_cost";
  /**
   * How quickly this surplus loses value if not activated
   */
  time_sensitivity?: "none" | "weeks" | "days" | "hours";
  [k: string]: unknown;
}
/**
 * Structured data for algorithmic capability matching (required at search time, can be AI-enriched from human input). Note: This is SEP's matching engine, not external AI agents.
 */
export interface CapabilityMatching {
  /**
   * Normalised list of outputs this surplus can produce (e.g., ['pitch_deck', 'brand_identity', 'goods_transport'])
   */
  capability_outputs: string[];
  /**
   * Quantified available capacity
   */
  capacity_available: {
    amount: number;
    unit: "hours" | "days" | "units" | "projects" | "trips" | "sessions";
    [k: string]: unknown;
  };
  /**
   * Sectors this surplus applies to (e.g., ['professional_services', 'creative', 'logistics'])
   */
  sector_tags?: string[];
  /**
   * Quick-filter flags (e.g., ['remote_only', 'uk_only', 'perishable', 'transport_required'])
   */
  constraint_flags?: string[];
  /**
   * Location for geographic matching
   */
  location?: {
    city?: string;
    region?: string;
    country?: string;
    coordinates?: {
      lat?: number;
      lon?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Details specific to service offerings
 */
export interface ServiceDetails {
  /**
   * Human-readable capacity description (e.g., '20 hours', '5 projects')
   */
  available_capacity?: string;
  /**
   * What this surplus can translate into for recipients
   */
  capability_mapping?: {
    /**
     * What the recipient gets (e.g., 'pitch_deck', 'goods_transport')
     */
    output: string;
    capacity_consumption?: CapacityConsumption;
    /**
     * What provider needs from recipient to deliver
     */
    requirements?: string[];
    /**
     * What recipient receives upon completion
     */
    deliverables?: string[];
    transport_route?: TransportRoute;
    [k: string]: unknown;
  }[];
  /**
   * What this capacity CANNOT translate into
   */
  skillset_boundaries?: string[];
  /**
   * How the service is delivered
   */
  delivery_method?: "remote" | "onsite" | "hybrid";
  /**
   * Notice required before starting (e.g., '2 weeks')
   */
  lead_time?: string;
  [k: string]: unknown;
}
/**
 * Estimated capacity required for this output
 */
export interface CapacityConsumption {
  /**
   * Human-readable estimate (e.g., '4-8 hours', '1 trip')
   */
  estimate?: string;
  /**
   * Numeric amount for computation (use midpoint of range)
   */
  amount?: number;
  /**
   * Unit matching the offering's capacity unit
   */
  unit?: "hours" | "days" | "units" | "projects" | "trips" | "sessions";
  /**
   * How confident is this estimate
   */
  confidence?: "exact" | "typical" | "estimated" | "variable";
  /**
   * Whether human must confirm capacity-to-output translation before commitment (almost always true)
   */
  requires_confirmation?: boolean;
  [k: string]: unknown;
}
/**
 * For goods_transport capability: the route this transport covers
 */
export interface TransportRoute {
  from?: {
    city?: string;
    region?: string;
    country?: string;
    [k: string]: unknown;
  };
  to?: {
    city?: string;
    region?: string;
    country?: string;
    [k: string]: unknown;
  };
  /**
   * Type of route coverage
   */
  route_type?: "point_to_point" | "corridor" | "regional" | "national";
  /**
   * How often this route runs (e.g., 'twice weekly', 'daily', 'on demand')
   */
  frequency?: string;
  capacity_per_trip?: {
    /**
     * Weight capacity (e.g., '500kg')
     */
    weight?: string;
    /**
     * Volume capacity (e.g., '2 cubic metres')
     */
    volume?: string;
    /**
     * Unit capacity (e.g., '4 pallets')
     */
    units?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Details specific to physical goods
 */
export interface PhysicalDetails {
  location?: {
    city?: string;
    region?: string;
    country?: string;
    coordinates?: {
      lat?: number;
      lon?: number;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Amount available (e.g., '500 units', '2 tonnes')
   */
  quantity?: string;
  /**
   * Total weight for transport planning
   */
  weight?: string;
  /**
   * Size for transport/storage planning
   */
  dimensions?: string;
  /**
   * Time sensitivity of the goods
   */
  perishability?: "none" | "weeks" | "days" | "hours";
  /**
   * Condition of the goods
   */
  condition?: "new" | "like_new" | "good" | "fair";
  /**
   * How long provider can hold the goods
   */
  storage_available_until?: string;
  /**
   * Whether provider will handle transport
   */
  transport_included?: boolean;
  transport_matching?: PhysicalTransportMatching;
  [k: string]: unknown;
}
/**
 * Information for matching transport surplus to move these goods
 */
export interface PhysicalTransportMatching {
  /**
   * Whether transport to recipient is needed (vs collection)
   */
  transport_required?: boolean;
  /**
   * Whether a third-party transport surplus can be matched to move these goods
   */
  transport_matchable?: boolean;
  transport_requirements?: {
    weight?: string;
    volume?: string;
    handling?: "standard" | "fragile" | "temperature_controlled" | "hazardous";
    /**
     * How flexible timing is (e.g., 'within 2 weeks', 'specific date required')
     */
    timing_flexibility?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Details specific to access/expertise offerings
 */
export interface AccessDetails {
  /**
   * Nature of the access being offered
   */
  access_type?: "advisory" | "mentoring" | "consulting" | "usage_rights";
  /**
   * How much time is available (e.g., '2 hours/week ongoing')
   */
  availability?: string;
  /**
   * Areas of expertise covered
   */
  domain?: string[];
  /**
   * How access is delivered (e.g., 'video calls', 'async messaging')
   */
  format?: string;
  /**
   * How long access is offered (e.g., '3 months', 'ongoing')
   */
  duration?: string;
  [k: string]: unknown;
}
/**
 * Limitations on when/how this can be exchanged
 */
export interface Constraints {
  /**
   * Geographic limitations (e.g., ['UK only', 'Europe'])
   */
  geographic?: string[];
  timing?: {
    available_from?: string;
    available_until?: string;
    blackout_periods?: string[];
    [k: string]: unknown;
  };
  /**
   * Industries provider won't work with
   */
  excluded_sectors?: string[];
  /**
   * Smallest viable exchange (e.g., '4 hours minimum')
   */
  minimum_engagement?: string;
  /**
   * Largest single exchange accepted
   */
  maximum_engagement?: string;
  chain_participation?: ChainParticipation;
  [k: string]: unknown;
}
/**
 * Preferences for multi-party exchange chain participation
 */
export interface ChainParticipation {
  /**
   * Maximum chain length this offering can participate in
   */
  max_chain_length?: number;
  /**
   * Minimum chain length (2 = direct exchange acceptable)
   */
  min_chain_length?: number;
  /**
   * Whether this offering can be matched as an intermediate step in a chain
   */
  can_be_intermediate?: boolean;
  /**
   * Preference for direct over chain matches (chains still acceptable)
   */
  prefers_direct?: boolean;
  [k: string]: unknown;
}
