/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Represents a multi-party exchange cycle where all participants both give and receive
 */
export interface ExchangeChain {
  /**
   * Unique identifier for this chain
   */
  id: string;
  /**
   * Current state of the chain lifecycle: draft (not yet proposed), proposed (sent to participants), confirming (awaiting confirmations), committed (all confirmed), executing (exchanges in progress), completed (all satisfied), or terminal failure states
   */
  status:
    | "draft"
    | "proposed"
    | "confirming"
    | "committed"
    | "executing"
    | "completed"
    | "discarded"
    | "abandoned"
    | "declined"
    | "cancelled"
    | "failed";
  /**
   * When this chain was proposed
   */
  created_at: string;
  /**
   * The exchanges that make up this chain, in order
   *
   * @minItems 2
   */
  edges: [ChainEdge, ChainEdge, ...ChainEdge[]];
  timing?: ChainTiming;
  metadata?: ChainMetadata;
  /**
   * Audit trail of state changes
   */
  history?: ChainEvent[];
  failure_info?: FailureInfo;
  compensation_plan?: CompensationPlan;
  [k: string]: unknown;
}
/**
 * A single exchange within the chain
 */
export interface ChainEdge {
  /**
   * Unique identifier for this edge
   */
  id: string;
  /**
   * Participant providing the offering
   */
  provider_id: string;
  /**
   * Participant receiving the offering
   */
  recipient_id: string;
  /**
   * Reference to the capability offering being exchanged
   */
  offering_id: string;
  /**
   * Copy of relevant offering details at time of chain creation
   */
  offering_snapshot?: {
    [k: string]: unknown;
  };
  /**
   * Current state of this edge: confirmation states, execution states, or terminal states (satisfied, skipped if restructured out, disputed, resolved)
   */
  status:
    | "proposed"
    | "provider_confirmed"
    | "recipient_confirmed"
    | "both_confirmed"
    | "in_progress"
    | "delivered"
    | "satisfied"
    | "skipped"
    | "disputed"
    | "resolved";
  confirmation?: {
    provider_confirmed_at?: string;
    recipient_confirmed_at?: string;
    [k: string]: unknown;
  };
  execution?: {
    started_at?: string;
    completed_at?: string;
    /**
     * Any notes about the execution
     */
    notes?: string;
    [k: string]: unknown;
  };
  satisfaction?: {
    /**
     * Provider's satisfaction with the exchange
     */
    provider_signal?: "satisfied" | "partially_satisfied" | "not_satisfied";
    /**
     * Recipient's satisfaction with what they received
     */
    recipient_signal?: "satisfied" | "partially_satisfied" | "not_satisfied";
    provider_feedback?: string;
    recipient_feedback?: string;
    [k: string]: unknown;
  };
  /**
   * Edge IDs that must complete before this edge can start
   */
  dependencies?: string[];
  /**
   * Compensation details if this edge fails or is skipped
   */
  compensation?: {
    /**
     * Compensation action taken or required
     */
    action?: "none_required" | "completed_independently" | "reversed" | "compensated" | "pending";
    /**
     * ID of compensating exchange if one was created
     */
    compensation_edge_id?: string;
    /**
     * Details about the compensation arrangement
     */
    notes?: string;
    [k: string]: unknown;
  };
  /**
   * Details when edge is in disputed or resolved state
   */
  dispute_details?: {
    /**
     * Category of dispute
     */
    dispute_type?:
      | "non_delivery"
      | "partial_delivery"
      | "quality_mismatch"
      | "timing_violation"
      | "scope_dispute"
      | "other";
    /**
     * When the dispute was raised
     */
    raised_at?: string;
    /**
     * Participant ID who raised the dispute
     */
    raised_by?: string;
    /**
     * When the dispute was resolved
     */
    resolved_at?: string;
    /**
     * Description of how the dispute was resolved
     */
    resolution?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Timing constraints and schedule for the chain
 */
export interface ChainTiming {
  /**
   * All participants must confirm by this time
   */
  confirmation_deadline?: string;
  execution_window?: {
    /**
     * Earliest date execution can begin
     */
    start?: string;
    /**
     * Latest date all exchanges must complete
     */
    end?: string;
    [k: string]: unknown;
  };
  /**
   * Specific timing for each edge
   */
  edge_schedules?: {
    edge_id?: string;
    scheduled_start?: string;
    scheduled_completion?: string;
    [k: string]: unknown;
  }[];
  /**
   * Circuit breaker configuration for automatic failure handling
   */
  circuit_breaker?: {
    /**
     * Days after scheduled completion before edge is considered timed out
     */
    edge_timeout_days?: number;
    /**
     * Number of disputed edges that triggers automatic chain failure
     */
    max_disputes_before_failure?: number;
    /**
     * Hours between automated health checks
     */
    health_check_interval_hours?: number;
    /**
     * Whether to attempt automatic chain restructuring on edge failure
     */
    auto_restructure_enabled?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Computed metadata about the chain
 */
export interface ChainMetadata {
  /**
   * Number of participants in the chain
   */
  participant_count?: number;
  /**
   * Whether any edge involves physical goods
   */
  includes_physical_goods?: boolean;
  /**
   * Regions involved in the chain
   */
  geographic_span?: string[];
  /**
   * How this chain was identified
   */
  proposed_by?: "algorithm" | "participant" | "broker";
  /**
   * Algorithm's confidence in this chain
   */
  match_score?: number;
  /**
   * Estimated probability of chain failure
   */
  risk_score?: number;
  [k: string]: unknown;
}
/**
 * An event in the chain's history
 */
export interface ChainEvent {
  timestamp: string;
  event_type:
    | "created"
    | "submitted"
    | "participant_confirmed"
    | "participant_declined"
    | "all_confirmed"
    | "execution_started"
    | "edge_started"
    | "edge_completed"
    | "edge_satisfied"
    | "edge_skipped"
    | "edge_disputed"
    | "edge_resolved"
    | "chain_restructured"
    | "chain_completed"
    | "chain_failed"
    | "chain_cancelled"
    | "chain_abandoned"
    | "health_check"
    | "timeout_warning";
  /**
   * Participant involved in this event (if applicable)
   */
  participant_id?: string;
  /**
   * Edge involved in this event (if applicable)
   */
  edge_id?: string;
  /**
   * Additional context
   */
  notes?: string;
  [k: string]: unknown;
}
/**
 * Details about chain failure if status is failed, abandoned, or cancelled
 */
export interface FailureInfo {
  /**
   * When the failure was determined
   */
  failed_at?: string;
  /**
   * Category of failure
   */
  failure_reason?:
    | "edge_timeout"
    | "edge_abandonment"
    | "unresolved_dispute"
    | "participant_withdrawal"
    | "cascade_failure"
    | "infrastructure_failure"
    | "confirmation_timeout"
    | "other";
  /**
   * Edge that triggered the failure, if applicable
   */
  failed_edge_id?: string;
  /**
   * Human-readable description of what went wrong
   */
  description?: string;
  [k: string]: unknown;
}
/**
 * Overall compensation strategy for the chain if it fails
 */
export interface CompensationPlan {
  /**
   * Overall compensation approach
   */
  strategy?: "restructure" | "partial_complete" | "full_unwind" | "settle_externally" | "no_action";
  /**
   * Current status of compensation plan
   */
  status?: "proposed" | "approved" | "executing" | "completed" | "rejected";
  /**
   * Whether participants must approve the compensation plan
   */
  requires_approval?: boolean;
  /**
   * Participant IDs who have approved the plan
   */
  approved_by?: string[];
  /**
   * Specific actions for each affected edge
   */
  actions?: {
    /**
     * Edge this action applies to
     */
    edge_id?: string;
    /**
     * Action to take for this edge
     */
    action?: "complete_independently" | "reverse" | "compensate" | "skip" | "no_action";
    /**
     * Details of the compensation action
     */
    description?: string;
    [k: string]: unknown;
  }[];
  /**
   * Additional notes about the compensation plan
   */
  notes?: string;
  [k: string]: unknown;
}
