/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a participant's need that could be fulfilled through activated surplus. The recipient assesses subjective value—is receiving this better than not receiving it? There are no exchange rates; each party decides independently whether the exchange is worthwhile.
 */
export interface Need {
  /**
   * Unique identifier for this need
   */
  id: string;
  /**
   * Category of need (mirrors offering types for matching)
   */
  type: "service" | "physical_good" | "access" | "space";
  /**
   * Identifier of the participant who has this need
   */
  participant: string;
  /**
   * Current status of the need
   */
  status: "active" | "partially_fulfilled" | "fulfilled" | "expired" | "withdrawn";
  /**
   * Short, human-readable title for the need
   */
  title?: string;
  /**
   * Detailed description of what is needed and why (supports AI interpretation)
   */
  description: string;
  /**
   * What the participant wants to achieve (outcome focus, not resource focus)
   */
  outcome_sought?: string;
  capability_links?: CapabilityLinks;
  service_need_details?: ServiceNeedDetails;
  physical_need_details?: PhysicalNeedDetails;
  access_need_details?: AccessNeedDetails;
  constraints?: Constraints;
  preferences?: Preferences;
  urgency?: Urgency;
  fulfilment_history?: FulfilmentHistory;
  inferred_signals?: InferredSignals;
  /**
   * When the need was first declared
   */
  created_at?: string;
  /**
   * When the need was last modified
   */
  updated_at?: string;
  /**
   * Who can see this need (public = browsable, network_only = authenticated members, agent_only = AI matching only)
   */
  visibility?: "public" | "network_only" | "agent_only";
  capability_matching: CapabilityMatching;
}
/**
 * Links to known capability outputs that could fulfil this need
 */
export interface CapabilityLinks {
  /**
   * Capability outputs the participant explicitly identified as fulfilling this need
   */
  explicit_matches?: {
    /**
     * Name of the capability output (e.g., 'pitch deck design', 'monthly bookkeeping')
     */
    capability_output: string;
    /**
     * Why this capability fits the need
     */
    fit_notes?: string;
  }[];
  /**
   * Capability outputs AI agents have identified as potential matches
   */
  inferred_matches?: {
    /**
     * Name of the capability output
     */
    capability_output: string;
    /**
     * AI confidence in this match (0 = no confidence, 1 = certain match)
     */
    confidence: number;
    /**
     * Why AI believes this capability could fulfil the need
     */
    reasoning?: string;
    /**
     * Whether participant has confirmed or rejected this inference
     */
    participant_confirmed?: boolean;
  }[];
  /**
   * Capability outputs that explicitly do NOT fit this need (refines future matching)
   */
  excluded_capabilities?: string[];
}
/**
 * Details specific to service needs
 */
export interface ServiceNeedDetails {
  /**
   * What the service should accomplish
   */
  scope_description?: string;
  /**
   * Participant's estimate of effort required (e.g., '10-20 hours')
   */
  estimated_effort?: string;
  /**
   * Specific deliverables the participant expects
   */
  deliverables_expected?: string[];
  /**
   * What the participant can provide to support delivery
   */
  inputs_available?: string[];
  /**
   * How the service should be delivered
   */
  delivery_preference?: "remote" | "onsite" | "hybrid" | "no_preference";
  /**
   * How much interaction is expected during delivery
   */
  collaboration_level?: "hands_off" | "light_touch" | "collaborative" | "embedded";
}
/**
 * Details specific to physical goods needs
 */
export interface PhysicalNeedDetails {
  /**
   * Amount needed (e.g., '50 units', '2 pallets')
   */
  quantity?: string;
  /**
   * Technical specifications for the goods
   */
  specifications?: {
    /**
     * Name of the specification attribute
     */
    attribute?: string;
    /**
     * Required value or range for this attribute
     */
    requirement?: string;
    /**
     * How strict this specification is
     */
    flexibility?: "exact" | "approximate" | "flexible";
  }[];
  /**
   * Acceptable condition levels
   */
  condition_accepted?: ("new" | "like_new" | "good" | "fair" | "any")[];
  /**
   * Where goods should be delivered
   */
  delivery_location?: {
    /**
     * City name
     */
    city?: string;
    /**
     * Region or county
     */
    region?: string;
    /**
     * Country name
     */
    country?: string;
    /**
     * Postal code for delivery
     */
    postcode?: string;
  };
  /**
   * Whether participant can collect goods themselves
   */
  can_collect?: boolean;
  /**
   * Maximum distance participant will travel for collection (in kilometres)
   */
  collection_radius_km?: number;
  /**
   * Any storage limitations (size, temperature, timing)
   */
  storage_constraints?: string;
}
/**
 * Details specific to access/expertise needs
 */
export interface AccessNeedDetails {
  /**
   * Nature of access needed
   */
  access_type_sought?: "advisory" | "mentoring" | "consulting" | "usage_rights" | "introduction";
  /**
   * Areas of expertise or access needed
   */
  domain?: string[];
  /**
   * How often access is needed (e.g., 'weekly', 'ad-hoc', 'one-off')
   */
  frequency?: string;
  /**
   * How long access is needed (e.g., '3 months', 'ongoing')
   */
  duration?: string;
  /**
   * Preferred interaction format (e.g., 'video calls', 'in-person', 'async')
   */
  format_preference?: string;
  /**
   * Specific questions or topics to address (helps matching)
   */
  specific_questions?: string[];
}
/**
 * Hard constraints that must be met (deal-breakers)
 */
export interface Constraints {
  /**
   * Geographic constraints for acceptable offerings
   */
  geographic?: {
    /**
     * Regions from which offerings are acceptable
     */
    accepted_regions?: string[];
    /**
     * Regions explicitly excluded
     */
    excluded_regions?: string[];
  };
  /**
   * Timing constraints for fulfilment
   */
  timing?: {
    /**
     * Latest acceptable fulfilment date
     */
    needed_by?: string;
    /**
     * Earliest acceptable start date
     */
    needed_after?: string;
    /**
     * Periods when participant cannot receive
     */
    blackout_periods?: string[];
  };
  /**
   * Requirements for acceptable providers
   */
  provider_requirements?: {
    /**
     * Minimum exchange history required
     */
    min_exchanges_completed?: number;
    /**
     * Minimum satisfaction rating required (0-5 scale)
     */
    min_satisfaction_rating?: number;
    /**
     * Whether provider must be verified
     */
    verification_required?: boolean;
    /**
     * Professional certifications required
     */
    required_certifications?: string[];
  };
  /**
   * Sectors the participant won't receive from
   */
  excluded_sectors?: string[];
  /**
   * Specific participant IDs to exclude
   */
  excluded_participants?: string[];
}
/**
 * Soft preferences that improve match quality but aren't required
 */
export interface Preferences {
  /**
   * Sectors preferred for matching
   */
  preferred_sectors?: string[];
  /**
   * Preferred experience level of provider
   */
  preferred_experience_level?: "any" | "junior" | "mid" | "senior" | "expert";
  /**
   * Preference for existing vs new exchange partners
   */
  relationship_preference?: "new_connection" | "existing_partner" | "vouched_only" | "no_preference";
  /**
   * Preferences for multi-party exchange chains
   */
  chain_participation?: {
    /**
     * Maximum multi-party chain length acceptable
     */
    max_chain_length?: number;
    /**
     * Whether to prefer direct over chain matches
     */
    prefer_direct?: boolean;
  };
  /**
   * Preferred communication style with provider
   */
  communication_style?: "formal" | "casual" | "no_preference";
}
/**
 * Time-sensitivity of the need
 */
export interface Urgency {
  /**
   * Self-declared priority level (treat with caution - gaming risk)
   */
  declared_priority?: "low" | "normal" | "high" | "critical";
  /**
   * Hard deadline if one exists
   */
  deadline?: string;
  /**
   * How firm the deadline is
   */
  deadline_type?: "hard" | "soft" | "preferred";
  /**
   * Objective factors that indicate urgency (used by AI to compute urgency score)
   */
  contextual_factors?: {
    /**
     * Type of factor (e.g., 'linked_to_perishable', 'blocking_other_work', 'seasonal_window')
     */
    factor?: string;
    /**
     * Details about the factor
     */
    description?: string;
  }[];
  /**
   * What participant will trade off for faster fulfilment
   */
  flexibility_for_speed?: {
    /**
     * Will accept partial fulfilment
     */
    accept_partial?: boolean;
    /**
     * Will accept less experienced providers
     */
    accept_less_experienced?: boolean;
    /**
     * Will accept longer multi-party chains
     */
    accept_longer_chain?: boolean;
    /**
     * Will accept different delivery format
     */
    accept_different_format?: boolean;
  };
  /**
   * AI-computed urgency score combining all factors (not self-reported, 0 = not urgent, 1 = extremely urgent)
   */
  computed_urgency_score?: number;
}
/**
 * Record of partial or complete fulfilment attempts
 */
export interface FulfilmentHistory {
  /**
   * How much of the need has been fulfilled (0-100%)
   */
  total_fulfilled_percentage?: number;
  /**
   * Individual fulfilment events
   */
  fulfilment_events?: {
    /**
     * ID of the exchange that provided fulfilment
     */
    exchange_id?: string;
    /**
     * Date when fulfilment occurred
     */
    fulfilled_at?: string;
    /**
     * What portion this exchange fulfilled
     */
    portion_fulfilled?: string;
    /**
     * Participant's satisfaction with this fulfilment
     */
    satisfaction?: "satisfied" | "partially_satisfied" | "not_satisfied";
  }[];
  /**
   * Matches that were proposed but declined (informs future matching)
   */
  declined_matches?: {
    /**
     * ID of the declined offering
     */
    offering_id?: string;
    /**
     * Date when match was declined
     */
    declined_at?: string;
    /**
     * Why the match was declined
     */
    reason?: string;
  }[];
}
/**
 * AI-derived signals that enrich matching (populated over time)
 */
export interface InferredSignals {
  /**
   * Other needs this participant has posted that suggest patterns
   */
  similar_needs_pattern?: string[];
  /**
   * Sectors this participant frequently exchanges with
   */
  sector_affinity?: {
    /**
     * Sector name
     */
    sector?: string;
    /**
     * Affinity score (0 = no affinity, 1 = strong affinity)
     */
    affinity_score?: number;
  }[];
  /**
   * Patterns in when participant posts needs
   */
  timing_patterns?: {
    /**
     * How far in advance participant typically posts needs
     */
    typical_lead_time?: string;
    /**
     * Seasonal patterns in need posting
     */
    seasonal_patterns?: string[];
  };
  /**
   * Inferred sensitivity to provider quality vs availability (0 = availability-focused, 1 = quality-focused)
   */
  quality_sensitivity?: number;
  /**
   * When these signals were last computed
   */
  last_inference_update?: string;
}
/**
 * Structured data for algorithmic capability matching (required at search time, can be AI-enriched from human input). Note: This is SEP's matching engine, not external AI agents.
 */
export interface CapabilityMatching {
  /**
   * Capability outputs that would fulfil this need (e.g., ['pitch_deck', 'brand_identity'])
   */
  capability_sought: string[];
  /**
   * Sectors relevant to this need
   */
  sector_tags?: string[];
  /**
   * Quick-filter constraint flags (e.g., ['remote_acceptable', 'uk_only', 'urgent'])
   */
  constraint_flags?: string[];
  /**
   * Location for geographic matching (especially for physical goods)
   */
  location?: {
    city?: string;
    region?: string;
    country?: string;
    [k: string]: unknown;
  };
  /**
   * Whether fulfilment via multi-party chain is acceptable
   */
  chain_acceptable?: boolean;
  /**
   * Maximum chain length acceptable if chain_acceptable is true
   */
  max_chain_length?: number;
  /**
   * For physical goods: whether third-party transport surplus can be matched to deliver
   */
  transport_acceptable?: boolean;
  [k: string]: unknown;
}
