/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a participant in the surplus exchange network, including identity, trust metrics, and network position
 */
export interface Participant {
  /**
   * Unique identifier for this participant
   */
  id: string;
  type: ParticipantType;
  /**
   * Current standing in the network
   */
  status: "probationary" | "active" | "suspended" | "withdrawn";
  /**
   * Date participant joined the network
   */
  joined_at: string;
  identity: Identity;
  profile?: Profile;
  network_position?: NetworkPosition;
  satisfaction_summary?: SatisfactionSummary;
  vouching?: Vouching;
  preferences?: Preferences;
  delegation?: Delegation;
  accountability?: Accountability;
  [k: string]: unknown;
}
/**
 * Participant type classification including category and sub-type
 */
export interface ParticipantType {
  /**
   * Primary category of participant
   */
  category: "human" | "organisation" | "agent";
  /**
   * Specific type within category
   */
  sub_type?: (
    | ("individual_consumer" | "individual_professional")
    | (
        | "sole_trader"
        | "small_business"
        | "medium_business"
        | "large_enterprise"
        | "non_profit"
        | "cooperative"
        | "public_sector"
      )
    | ("delegated_agent" | "autonomous_buyer" | "multi_agent_network")
  ) &
    string;
  /**
   * Employee count for organisations
   */
  employee_count_band?: "1" | "2-10" | "11-50" | "51-250" | "250+";
  [k: string]: unknown;
}
/**
 * Verified identity information (Layer 1 trust)
 */
export interface Identity {
  /**
   * Name shown to other participants
   */
  display_name: string;
  /**
   * Registered legal name (may differ from display name)
   */
  legal_name?: string;
  /**
   * Current verification state
   */
  verification_status: "unverified" | "pending" | "verified" | "lapsed";
  /**
   * How identity was verified
   */
  verification_method?: "companies_house" | "professional_body" | "kyb_provider" | "manual_review";
  /**
   * Date verification was completed
   */
  verified_at?: string;
  /**
   * Company registration number (if applicable)
   */
  registration_number?: string;
  /**
   * Professional body memberships
   */
  professional_memberships?: {
    /**
     * Professional body name (e.g., 'ICAEW', 'Law Society')
     */
    body?: string;
    /**
     * Membership or registration number
     */
    membership_id?: string;
    /**
     * Whether membership has been verified
     */
    verified?: boolean;
    [k: string]: unknown;
  }[];
  /**
   * Primary legal jurisdiction (e.g., 'UK', 'Ireland')
   */
  jurisdiction?: string;
  [k: string]: unknown;
}
/**
 * Public-facing profile information
 */
export interface Profile {
  /**
   * Brief description of the business
   */
  headline?: string;
  /**
   * Detailed description of the business and what they offer
   */
  description?: string;
  /**
   * Industry sectors the participant operates in
   */
  sectors?: string[];
  location?: {
    city?: string;
    region?: string;
    country?: string;
    [k: string]: unknown;
  };
  /**
   * Business website
   */
  website?: string;
  contact?: {
    /**
     * Name of primary contact person
     */
    primary_name?: string;
    /**
     * Role of primary contact
     */
    primary_role?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Metrics derived from exchange activity (Layer 2 trust)
 */
export interface NetworkPosition {
  /**
   * Number of distinct participants exchanged with
   */
  exchange_partners_count?: number;
  /**
   * Proportion of partners exchanged with more than once
   */
  repeat_partner_rate?: number;
  /**
   * Distribution of partners across sectors
   */
  partner_diversity?: {
    /**
     * Number of distinct sectors exchanged with
     */
    sector_count?: number;
    /**
     * Breakdown by offering type (service, physical_good, access, space)
     */
    offering_type_distribution?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  /**
   * Number of participants reachable within 2 degrees of connection
   */
  network_reach?: number;
  /**
   * Number of exchanges where this participant provided
   */
  exchanges_as_provider?: number;
  /**
   * Number of exchanges where this participant received
   */
  exchanges_as_recipient?: number;
  /**
   * Number of multi-party chains participated in
   */
  chain_participation_count?: number;
  /**
   * Date of most recent completed exchange
   */
  last_exchange_at?: string;
  /**
   * When these metrics were last computed
   */
  metrics_updated_at?: string;
  [k: string]: unknown;
}
/**
 * Aggregated satisfaction signals (Layer 3 trust)
 */
export interface SatisfactionSummary {
  as_provider?: SatisfactionBreakdown;
  as_recipient?: SatisfactionBreakdown1;
  /**
   * Proportion of exchanges where this participant provided satisfaction signal
   */
  response_rate?: number;
  [k: string]: unknown;
}
/**
 * Satisfaction signals received when providing
 */
export interface SatisfactionBreakdown {
  /**
   * Total signals received
   */
  total?: number;
  /**
   * Count of 'satisfied' signals
   */
  satisfied?: number;
  /**
   * Count of 'partially satisfied' signals
   */
  partially_satisfied?: number;
  /**
   * Count of 'not satisfied' signals
   */
  not_satisfied?: number;
  [k: string]: unknown;
}
/**
 * Satisfaction signals received when receiving
 */
export interface SatisfactionBreakdown1 {
  /**
   * Total signals received
   */
  total?: number;
  /**
   * Count of 'satisfied' signals
   */
  satisfied?: number;
  /**
   * Count of 'partially satisfied' signals
   */
  partially_satisfied?: number;
  /**
   * Count of 'not satisfied' signals
   */
  not_satisfied?: number;
  [k: string]: unknown;
}
/**
 * Sponsorship relationships
 */
export interface Vouching {
  /**
   * Participants who have vouched for this participant
   */
  vouched_by?: {
    /**
     * ID of the vouching participant
     */
    participant_id?: string;
    /**
     * Date vouch was given
     */
    vouched_at?: string;
    /**
     * Nature of relationship (e.g., 'former client', 'professional contact')
     */
    relationship?: string;
    [k: string]: unknown;
  }[];
  /**
   * Participants this participant has vouched for
   */
  vouches_given?: {
    /**
     * ID of participant vouched for
     */
    participant_id?: string;
    vouched_at?: string;
    /**
     * Current status of vouched participant (affects voucher reputation)
     */
    outcome?: "active" | "suspended" | "withdrawn";
    [k: string]: unknown;
  }[];
  /**
   * How many more newcomers this participant can vouch for
   */
  vouching_capacity?: number;
  [k: string]: unknown;
}
/**
 * Matching and communication preferences
 */
export interface Preferences {
  matching?: {
    /**
     * Maximum multi-party chain length willing to participate in
     */
    max_chain_length?: number;
    /**
     * Minimum exchange count required from potential partners
     */
    min_partner_exchanges?: number;
    /**
     * Sectors preferred for matching
     */
    preferred_sectors?: string[];
    /**
     * Sectors to exclude from matching
     */
    excluded_sectors?: string[];
    [k: string]: unknown;
  };
  communication?: {
    /**
     * How to notify of potential matches
     */
    match_notification?: "immediate" | "daily_digest" | "weekly_digest";
    /**
     * Preferred communication channels
     */
    preferred_channels?: ("email" | "platform_message" | "webhook")[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Agent delegation configuration (Phase 2+). Null or absent for Phase 1 human-only participants.
 */
export interface Delegation {
  /**
   * Whether this participant uses delegated AI agents
   */
  uses_delegated_agents?: boolean;
  /**
   * Identifiers of registered delegated agents
   */
  agent_identifiers?: string[];
  bounds?: DelegationBounds;
  /**
   * When delegation was enabled
   */
  enabled_since?: string;
  [k: string]: unknown;
}
/**
 * Limits on what delegated agents can do
 */
export interface DelegationBounds {
  offering_creation?: {
    enabled?: boolean;
    /**
     * Offering categories agent can create
     */
    permitted_categories?: string[];
    require_human_review?: boolean;
    review_window_hours?: number;
    [k: string]: unknown;
  };
  need_creation?: {
    enabled?: boolean;
    permitted_categories?: string[];
    require_human_review?: boolean;
    [k: string]: unknown;
  };
  match_confirmation?: {
    auto_confirm_enabled?: boolean;
    conditions?: {
      max_chain_length?: number;
      require_established_partners?: boolean;
      min_partner_trust_score?: number;
      excluded_categories?: string[];
      [k: string]: unknown;
    };
    override_window_hours?: number;
    [k: string]: unknown;
  };
  satisfaction_signals?: {
    agent_can_draft?: boolean;
    agent_can_submit?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Accountability chain linking participant to responsible human/legal entity
 */
export interface Accountability {
  /**
   * How accountability is established
   */
  type: "self" | "principal" | "operator" | "legal_entity";
  /**
   * ID of primary accountable human (for agent participants)
   */
  primary_human_id?: string;
  /**
   * ID of accountable legal entity
   */
  legal_entity_id?: string;
  /**
   * Name of accountable legal entity
   */
  legal_entity_name?: string;
  /**
   * Human contacts for escalation/disputes
   */
  escalation_contacts?: {
    name?: string;
    email?: string;
    phone?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
