/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Trust tier levels: PROBATIONARY (new, limited), ESTABLISHED (proven track record), ANCHOR (high-trust, can vouch)
 */
export type TrustTier = "probationary" | "established" | "anchor";

/**
 * Comprehensive trust profile for a participant in the surplus exchange network, tracking tier status, track record, vouching relationships, and exposure limits
 */
export interface TrustProfile {
  /**
   * Unique identifier linking to participant.schema.json
   */
  participant_id: string;
  /**
   * Current trust tier determining exposure limits and capabilities
   */
  current_tier: "probationary" | "established" | "anchor";
  track_record: TrackRecord;
  /**
   * Chronological record of tier changes with reasons
   */
  tier_history?: TierChange[];
  vouching?: VouchingRecord;
  limits: ExposureLimits;
  timestamps: ProfileTimestamps;
  [k: string]: unknown;
}
/**
 * Historical performance metrics for this participant
 */
export interface TrackRecord {
  /**
   * Total number of exchange chains successfully completed
   */
  chains_completed: number;
  /**
   * Number of chains that failed due to this participant's action or inaction
   */
  chains_failed: number;
  /**
   * Number of chains currently executing
   */
  chains_in_progress?: number;
  satisfaction_received?: SatisfactionMetrics;
  /**
   * Proportion of commitments delivered within agreed timeframe. Null when no deliveries yet.
   */
  on_time_rate?: number | null;
  /**
   * Average number of participants in chains this participant has joined
   */
  average_chain_size?: number | null;
  /**
   * Aggregate of subjective value exchanged (for tier assessment only, not shared publicly)
   */
  total_value_exchanged?: {
    /**
     * Count of exchanges where this participant provided value
     */
    as_provider?: number;
    /**
     * Count of exchanges where this participant received value
     */
    as_recipient?: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Aggregated satisfaction signals received from exchange partners
 */
export interface SatisfactionMetrics {
  /**
   * Total number of satisfaction signals received
   */
  total_signals?: number;
  /**
   * Number of 'satisfied' signals
   */
  satisfied_count?: number;
  /**
   * Number of 'partially satisfied' signals
   */
  partially_satisfied_count?: number;
  /**
   * Number of 'not satisfied' signals
   */
  not_satisfied_count?: number;
  /**
   * Proportion of signals that were 'satisfied' (computed: satisfied_count / total_signals). Null when no signals received.
   */
  satisfaction_rate?: number | null;
  [k: string]: unknown;
}
/**
 * Record of a tier change event
 */
export interface TierChange {
  /**
   * Previous tier (null for initial assignment)
   */
  from_tier: TrustTier | null;
  /**
   * Trust tier levels: PROBATIONARY (new, limited), ESTABLISHED (proven track record), ANCHOR (high-trust, can vouch)
   */
  to_tier: "probationary" | "established" | "anchor";
  /**
   * When the tier change occurred
   */
  changed_at: string;
  /**
   * Reason for the tier change
   */
  reason:
    | "initial_join"
    | "track_record_threshold"
    | "time_in_network"
    | "vouching_qualification"
    | "network_contribution"
    | "failed_chain"
    | "low_satisfaction"
    | "inactivity"
    | "dispute_resolution"
    | "manual_review";
  /**
   * Additional context for the tier change
   */
  details?: string;
  /**
   * What triggered the tier change
   */
  changed_by?: "system" | "admin" | "automatic_promotion" | "automatic_demotion";
  [k: string]: unknown;
}
/**
 * Complete vouching relationships (given and received)
 */
export interface VouchingRecord {
  /**
   * Vouches this participant has received from others
   */
  vouched_by?: VouchReceived[];
  /**
   * Vouches this participant has given to others
   */
  vouched_for?: VouchGiven[];
  /**
   * How many more participants this member can currently vouch for
   */
  vouching_capacity?: number;
  /**
   * Track record of vouching quality (based on outcomes of vouched participants)
   */
  vouching_reputation?: number | null;
  [k: string]: unknown;
}
/**
 * Record of a vouch received from another participant
 */
export interface VouchReceived {
  /**
   * Participant ID of the vouching member
   */
  voucher_id: string;
  /**
   * Trust tier levels: PROBATIONARY (new, limited), ESTABLISHED (proven track record), ANCHOR (high-trust, can vouch)
   */
  voucher_tier_at_time?: "probationary" | "established" | "anchor";
  /**
   * Date the vouch was given
   */
  vouched_at: string;
  /**
   * Nature of the relationship (e.g., 'former client', 'industry peer', 'professional contact')
   */
  relationship?: string;
  /**
   * Current status of this vouch
   */
  status?: "active" | "withdrawn" | "expired";
  [k: string]: unknown;
}
/**
 * Record of a vouch given to another participant
 */
export interface VouchGiven {
  /**
   * Participant ID of the member being vouched for
   */
  vouchee_id: string;
  /**
   * Date the vouch was given
   */
  vouched_at: string;
  /**
   * Nature of the relationship
   */
  relationship?: string;
  /**
   * Current status of the vouched participant (affects voucher's reputation)
   */
  vouchee_current_status?: "active" | "suspended" | "withdrawn";
  /**
   * Trust tier levels: PROBATIONARY (new, limited), ESTABLISHED (proven track record), ANCHOR (high-trust, can vouch)
   */
  vouchee_current_tier?: "probationary" | "established" | "anchor";
  /**
   * Assessment of whether this vouch was well-placed
   */
  outcome_assessment?: "positive" | "neutral" | "negative";
  [k: string]: unknown;
}
/**
 * Current exposure limits based on tier and track record
 */
export interface ExposureLimits {
  /**
   * Maximum number of participants in chains this member can join
   */
  max_chain_size: number | null;
  /**
   * Maximum days allowed for chain execution. Null indicates no limit (anchor tier).
   */
  max_execution_window_days: number | null;
  /**
   * Maximum number of chains this participant can be active in simultaneously
   */
  max_concurrent_chains: number | null;
  /**
   * Whether this participant can vouch for new members
   */
  can_vouch?: boolean;
  /**
   * Whether this participant requires a vouch to participate
   */
  requires_vouching?: boolean;
  /**
   * Whether limits have been manually adjusted from tier defaults
   */
  limits_overridden?: boolean;
  /**
   * Reason for manual limit override (if applicable)
   */
  override_reason?: string | null;
  [k: string]: unknown;
}
/**
 * Key dates for this participant's trust profile
 */
export interface ProfileTimestamps {
  /**
   * When the participant joined the network
   */
  joined_at: string;
  /**
   * When the current tier was assigned
   */
  tier_updated_at?: string;
  /**
   * Most recent exchange activity (chain joined, completed, or satisfaction given)
   */
  last_activity_at?: string;
  /**
   * When this participant last vouched for someone (if applicable)
   */
  last_vouched_at?: string | null;
  /**
   * When this trust profile was last recalculated
   */
  profile_updated_at?: string;
  [k: string]: unknown;
}
